name: download and process Videos and Upload to S3

on: push

jobs:
  download-and-upload:
    environment: my_env
    permissions:
      contents: 'read'
      actions: 'read'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install pip dependencies
    - name: Install Dependencies
      run: |
         pip install pytube



    # Install apt dependencies if cache is not found
    - name: Install AWS CLI and FFmpeg
      if: steps.cache-apt.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli ffmpeg


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        mask-aws-account-id: 'no'



    - name: Run download_videos
      run: python download_videos.py  # Replace 'your_script_name.py' with the name of your Python script


    - name: Run process Videos
      run: |
        chmod +x process.sh
        bash process.sh

    - name: Upload Output Folder to S3
      run: aws s3 sync DavidAlvareeezy2/ s3://${{ secrets.S3_BUCKET_NAME }}/DavidAlvareeezy2/ 
