name: Transcribe Videos and Upload to S3

on: push

jobs:
  transcribe-and-upload:
    environment: my_env
    permissions:
      contents: 'read'
      actions: 'read'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install boto3
        pip install pytube

    
    
    - name: Install AWS CLI
      run: sudo apt-get install awscli

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        mask-aws-account-id: 'no'



    - name: Run download_videos
      run: python download_videos.py  # Replace 'your_script_name.py' with the name of your Python script


    - name: Run process Videos
      run: |
        chmod +x process.sh
        bash process.sh

    - name: Upload Output Folder to S3
      run: aws s3 sync FLAGRANT_final1/ s3://${{ secrets.S3_BUCKET_NAME }}/FLAGRANT_final1/ 
